# Generated by Django 2.2.4 on 2023-03-21 00:27

import Department.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Department', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('token', models.CharField(auto_created=True, blank=True, default='', max_length=100)),
                ('active', models.BooleanField(auto_created=True, default=True)),
                ('username', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True, verbose_name='用户名')),
                ('entity_super', models.BooleanField(default=False)),
                ('system_super', models.BooleanField(default=False)),
                ('department', models.ForeignKey(on_delete=models.SET(Department.models.Department.root), to='Department.Department')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Department.Entity')),
            ],
        ),
    ]
