# Generated by Django 2.2.4 on 2023-03-22 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.CharField(auto_created=True, blank=True, default='', max_length=200),
        ),
    ]
