# Generated by Django 2.2.4 on 2023-03-26 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_auto_20230322_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='asset_super',
            field=models.BooleanField(default=False),
        ),
    ]
