# Generated by Django 2.2.4 on 2023-03-27 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_user_asset_super'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='asset_super',
        ),
    ]
