# Generated by Django 2.2.4 on 2023-03-29 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0007_remove_user_asset_super'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='asset_super',
            field=models.BooleanField(default=False),
        ),
    ]
