# Generated by Django 2.2.4 on 2023-03-22 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Department', '0002_department_entity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Department.Entity'),
        ),
    ]
