# Generated by Django 2.2.4 on 2023-03-26 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Department', '0003_auto_20230322_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='entity',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
