# Generated by Django 2.2.4 on 2023-03-27 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Department', '0004_auto_20230326_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='entity',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
