# Generated by Django 2.2.4 on 2023-03-28 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Department', '0008_auto_20230328_0230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
