# Generated by Django 2.2.4 on 2023-03-29 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Department', '0009_auto_20230328_0231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='name',
            field=models.CharField(max_length=128),
        ),
    ]
